import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { SanityLive } from "@/sanity/lib/live";
import { Toaster } from "react-hot-toast";
// import { VisualEditing } from "next-sanity";
import { draftMode } from "next/headers";
// import DisableDraftMode from "@/components/DisableDraftMode";

const poppins = localFont({
    src: "./fonts/Poppins.woff2",
    variable: "--font-poppins",
    weight: "400",
    preload: false,
});

export const metadata: Metadata = {
    title: "Ecommerce App for Shoppers",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <ClerkProvider>
            <html lang="en">
                <body className={`${poppins.variable} antialiased`}>
                    {(await draftMode()).isEnabled && (
                        <>
                            {/* <DisableDraftMode />
                            <VisualEditing /> */}
                        </>
                    )}
                    {children}
                    <Toaster
                        position="bottom-right"
                        toastOptions={{
                            style: {
                                background: "#000000",
                                color: "#fff",
                            },
                        }}
                    />
                    <SanityLive />
                </body>
            </html>
        </ClerkProvider>
    );
}

